spring:
  application:
    name: user-profile
  docker:
    compose:
      file: compose.yaml
      lifecycle-management: start_only
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/userprofile
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: secret
